### ISSUE TITLE
Received this message today.

### ISSUE THREAD

**Issue by ankurghai** [Dam998/shopify-monitor#4]
blendus.com has an high level of protection from monitors, please notify Dam998 by opening an issue on github [https://github.com/Dam998/shopify-monitor]

**Comment by Dam998** [comment]
Hi ankurghai,
You got that message because blendus.com isn't a shopify site, maybe you're looking for blendsus.com?

However, if you like my job and if you want to support me, you can buy me a coffee on my [new page] (https://www.buymeacoffee.com/Dam998)
Or, if you want, you can become a member of my coffee group, members get some benefits, you can read them on my page

I hope to see you inside!

If you have any questions, ask, I'm here😉

**Comment by ankurghai** [comment]
sorry my bad. and surely mate, i'll join it. I am having a reselling store and planning to go main stream in india in july-august. i am setting up my internal services and would really love working with you in future. please do let me know if you have any experience in creating Supreme API as well.
